### ISSUE TITLE
requseting the image source

### ISSUE THREAD

**Issue by jinnmori** [kooriookami/yugioh-card#4]
hi i would like to know please, how i get the source images for the cards in this website https://ygo.ygosgs.com/#/yugioh? i really in need for it

**Comment by kooriookami** [comment]
This is the link: https://images.ygoprodeck.com/images/cards_cropped/10000000.jpg
Just replace the card password to any other cards.

**Comment by kooriookami** [comment]
The database is from YGO Omega: https://duelistsunite.org/omega/OmegaDB.cdb
The same card may have different passwords, cause a card could have many Altered Arts. All of these Altered Arts only have one offical password. But we need to figure out which Altered Arts users want to show. So using different password can solve it.

**Comment by kooriookami** [comment]
Oh, that website is running by other people now. I have been a long time not to manage it. [OmegaDB.cdb](https://duelistsunite.org/omega/OmegaDB.cdb) also includes jp text, you can open it with Navicat.

**Comment by kooriookami** [comment]
The manager is @pf666nb. Actually, there's no one website doing better than this. :D

**Comment by kooriookami** [comment]
Noop, it's not a open source project. There is a fee to use this site.
